export const BASE_URI = "http://localhost:8000";
export const PARAM_CLIENT= "/clients";
export const PARAM_PRODUCT= "/products";
export const PARAM_CATEGORY= "/categories";
export const PARAM_SIZE= "/sizes";
export const PARAM_WAREHOUSE= "/warehouse";
export const PARAM_USER= "/user";
export const PARAM_ORDER= "/orders";
export const PARAM_PRODUCT_WAREHOUSE= "/product-warehouse";